### ISSUE TITLE
/routers/router.go第26行报错

### ISSUE THREAD

**Issue by zhanghongtong** [EDDYCJY/go-gin-example#1]
麻烦问下第26行   
`r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))`  
报错：
` cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
	sse.Event does not implement render.Render (missing WriteContentType method)`
是怎么回事呢？

**Comment by EDDYCJY** [comment]
@zhanghongtong 你好，是在自己本地另外新建的项目测试吗？

可能你需要更新一下 `gin`，因为 `gin-swagger` 对版本有一定的要求

另外我直接`go get -u github.com/EDDYCJY/go-gin-example` 是可以正常运行的

**Comment by zhanghongtong** [comment]
@EDDYCJY 是我在本地新建的项目，目前gin的版本为v1.2，还是会报错`cannot use sse.Event literal (type sse.Event) as type render.Render in argument to c.Render:
	sse.Event does not implement render.Render (missing WriteContentType method)
`

**Comment by EDDYCJY** [comment]
@zhanghongtong 先执行 `go get -u github.com/gin-gonic/gin`更新，再尝试

**Comment by zhanghongtong** [comment]
@EDDYCJY  `go get -u github.com/EDDYCJY/go-gin-example`是可以运行的，但是我将您的项目中`/vendor`下的`github.com/gin-gonic/gin`复制出来粘贴到到我的目录下，还是会报错

**Comment by zhanghongtong** [comment]
@EDDYCJY 刚才看了一下，报错的位置是 `src/github.com/gin-gonic/gin/context.go:719:24`，这是gin的源码不对？？？

**Comment by EDDYCJY** [comment]
@zhanghongtong 是的，老铁 提 issues 要把 错误提示、涉及代码提供一下。否则作者很难判别，我只能依照你给的错误描述给你意见。

**由于看不到代码，我给你一个排查步骤：**

0、备份之前有问题的代码和注解
1、检查 gin、gin-swagger、swag...等包的安装正常
2、将你的API注解最简化（参见 [example](https://github.com/swaggo/gin-swagger/blob/master/example/api/api.go)）用于测试功能
3、重新生成swag所需文件，检查与 [example](https://github.com/swaggo/gin-swagger/tree/master/example/docs) 里的是否一致
4、成功了，就把你之前的注解拿过来排除解决

我认为一步步排查下来，你应该可以成功解决问题了
因为拉了 `go-gin-example` 没有问题，说明运行环境OK，那就是项目依赖包或代码、注解的问题

---

如果还是无法解决，建议老铁提供一下简化后的代码，便于我帮助你排查。

**Comment by zhanghongtong** [comment]
@EDDYCJY ，额，我试了各种方法都不行，然后准备传git之前执行了一下 `govendor add +external` 就可以了，所以是当安装了vendor之后依赖目录就从 `$GOPATH/src` 变更为当前项目下的`/vendor`目录了么？

**Comment by EDDYCJY** [comment]
@zhanghongtong 是的，如果当前项目下含 `vendor` 目录，将优先读取

**Comment by EDDYCJY** [comment]
@zhanghongtong 建议你检查下，估计是你未使用 `vendor` 前，依赖的$GOPATH的第三方依赖包存在问题

**Comment by zhanghongtong** [comment]
@EDDYCJY 查出来了，是我在使用IDE的时候在IDE内修改了GOPATH所以导致依赖加载不到的原因

**Comment by EDDYCJY** [comment]
@zhanghongtong :+1: :+1: :+1:

**Comment by zhanghongtong** [comment]
@EDDYCJY Goland自己有GOPATH的设置，跟真机上的设置有时会不一样，稍不注意就遗漏了

**Comment by EDDYCJY** [comment]
@zhanghongtong IDE是个好东西 但要对它熟悉 不要过度强依赖 

问题已解决，我关闭了 :100:
