### ISSUE TITLE
Swagger init 重新生成的时候

### ISSUE THREAD

**Issue by hg19840211** [eddycjy/go-gin-example#100]
$ swag init
2020/03/12 14:45:32 Generate swagger docs....
2020/03/12 14:45:32 Generate general API Info, search dir:./
2020/03/12 14:45:32 ParseComment error in file routers\api\v1\tag.go :can not find schema type: "v1.file"

**Comment by hg19840211** [comment]
需要注意版本 v1.6.5 是报错的 降级就好了

**Comment by gaojiankang** [comment]
我现在用的是1.6.7，把body改成formData就行了
// @Summary Import article tag
// @Produce  json
// @Param file formData file true "Excel File"
