### ISSUE TITLE
models article delete细节问题

### ISSUE THREAD

**Issue by bingoIsCoder** [eddycjy/go-gin-example#104]
`db.Where("id = ?", id).Delete(Article{})`
是不是应该这样比较好呀：
`db.Where("id = ?", id).Delete(&Article{})`

**Comment by xy-ly** [comment]
db. Delete(&Article{ID:id})
我觉得这样也行呢

**Comment by eddycjy** [comment]
@bingoIsCoder @xy-ly 都行，gorm 支持多种方式的，达到目的（或团队规范一致即可）。
