### ISSUE TITLE
jwt的验证为什么不是从header里获取

### ISSUE THREAD

**Issue by PaleBlueYk** [eddycjy/go-gin-example#119]
https://github.com/eddycjy/go-gin-example/blob/63963976dee04ac80a5c0ad50cc85bc2ba80034f/middleware/jwt/jwt.go#L20
这个为什么是`Query Params`里,验证一般不是该放在`header`里吗?
```
token := c.Request.Header.Get("token")
```

**Comment by baiyuxiong** [comment]
改一下就可以了：
const BEARER_SCHEMA = "Bearer "
authHeader := c.GetHeader("Authorization")
token := authHeader[len(BEARER_SCHEMA):]
