### ISSUE TITLE
关于middleware中jwt的一个小问题

### ISSUE THREAD

**Issue by xhochipe** [EDDYCJY/go-gin-example#12]
claims, err := util.ParseToken(token)
			if err != nil {
				code = e.ERROR_AUTH_CHECK_TOKEN_FAIL
			} else if time.Now().Unix() > claims.ExpiresAt {
				code = e.ERROR_AUTH_CHECK_TOKEN_TIMEOUT
			}

这块逻辑好像有点问题。如果token过期的话，err就不为空,里面也会有过期错误

	if !tokenClaims.Valid {
		if ve, ok := err.(*jwt.ValidationError); ok {
			if ve.Errors&jwt.ValidationErrorMalformed != 0 {
				code = e.ERROR_AUTH_TOKEN
			} else if ve.Errors&(jwt.ValidationErrorExpired|jwt.ValidationErrorNotValidYet) != 0 {
				code = e.ERROR_AUTH_TOKEN_TIMEOUT
			}
		}
	}
我现在是这样处理的

**Comment by EDDYCJY** [comment]
感谢您的反馈
我看了一下您提交的 issue 代码，我认为不够简洁和直观，有更好的解决方案
因此我提交了另外一版用于修复这个 BUG

具体代码可见：https://github.com/EDDYCJY/go-gin-example/blob/master/middleware/jwt/jwt.go
