### ISSUE TITLE
replacing callback `gorm:update_time_stamp`

### ISSUE THREAD

**Issue by bencen** [EDDYCJY/go-gin-example#13]
[info] replacing callback `gorm:update_time_stamp` from /data/go/src/github.com/EDDYCJY/go-gin-example/models/models.go:40
[info] replacing callback `gorm:update_time_stamp` from /data/go/src/github.com/EDDYCJY/go-gin-example/models/models.go:41
[info] replacing callback `gorm:delete` from /data/go/src/github.com/EDDYCJY/go-gin-example/models/models.go:42

这个是什么原因？

**Comment by EDDYCJY** [comment]
@bencen 这个 info 日志产生的原因是由于在我们在 models.go 中设置了自定义 callbacks，因此 gorm 自动输出的提醒日志

并不会有其他的副作用
