### ISSUE TITLE
问个其他的问题

### ISSUE THREAD

**Issue by Devying** [EDDYCJY/go-gin-example#16]
redigo 使用 hgetall后怎么处理结果呢

**Comment by EDDYCJY** [comment]
@Devying 这样子使用： `redis.StringMap(conn.Do("HGETALL", key))`

**Comment by Devying** [comment]
@EDDYCJY 我用的是ByteSlices

**Comment by EDDYCJY** [comment]
@Devying `HGETALL` 具体使用什么方法转换，根据你的实际业务场景选用就行了

**Comment by Devying** [comment]
@EDDYCJY 你的方法更简单一些，对了发现文档有点难理解，如果做redis别的操作有什么好的建议吗

**Comment by Devying** [comment]
像这个方法redis.StringMap(conn.Do("HGETALL", key)) 文档上写的参数是两个，第二个是err。怎么没传呢

**Comment by Devying** [comment]
好的非常感谢

**Comment by Devying** [comment]
@EDDYCJY 我刚认真看了一下文档，一下子豁然开朗，很清楚了，我准备用用看
