### ISSUE TITLE
大佬 为什么你数据库连接都不关闭的?

### ISSUE THREAD

**Issue by luodaozhang** [EDDYCJY/go-gin-example#18]
emm 都不关闭数据库连接的吗

**Comment by iflamed** [comment]
看了一下 CloseDB 没有调用

**Comment by EDDYCJY** [comment]
@luodaozhang @iflamed 首先需要有个基础概念，如下：

`sql.Open()` 实际上不建立与数据库的任何连接。也不验证驱动程序连接参数。相反，它只是准备数据库抽象以供以后使用。当第一次需要时，将懒惰地建立与底层数据库实例的第一个实际连接

---

在本项目中，我们将 `sql.DB` 视为一个长期使用的包全局对象，它是一个连接池。不需要频繁 `Open()` 和 `Close()`，需要的是为不同的数据库请求返回不同的连接句柄

而每次都 `defer db.Close()` 的行为更适合当该连接句柄已超出其生存函数时，应当关闭

那么显然，用法上就不一样了

**Comment by Devying** [comment]
使用的是长链接。只有程序终止的时候才调用close。
