### ISSUE TITLE
您好，为什么我的sql语句会复用呢？models.go 配置文件一样的

### ISSUE THREAD

**Issue by sun-wenming** [EDDYCJY/go-gin-example#19]
第一次执行
```
 UPDATE `topic` SET `modified_at` = '1543033067', `modified_by` = '1', `name` = '主题名称', `state` = '1'  WHERE `topic`.`deleted_at` IS NULL AND ((id = '1' ))
```
第五次执行
```
UPDATE `topic` SET `modified_at` = '1543033071', `modified_by` = '1', `name` = '主题名称', `state` = '1'  WHERE `topic`.`deleted_at` IS NULL AND ((id = '1' ) AND (id = '1' ) AND (id = '1' ) AND (id = '1' ) AND (id = '1' ))
```

附带项目地址。 麻烦大佬了。谢谢。
[gin-blog](https://github.com/sun-wenming/gin-blog)

**Comment by EDDYCJY** [comment]
@sun-wenming 你还需要更多的信息给我，这样子我才能更好的帮助你 Debug。希望你能够提供如下信息：

- 请求的是哪个接口（调用的哪个方法）？
- 接口的入参是怎么样的？
- 数据库的表初始化 SQL

**Comment by EDDYCJY** [comment]
简单来说，就是我希望能够模拟与您一模一样的情况

**Comment by sun-wenming** [comment]
1. 请求的接口为 `http://localhost:8000/api/v1/topics/{id}` 调用的方法为 \
`gin-blog\routers\api\v1\topic.go`
[EditTopic 方法](https://github.com/sun-wenming/gin-blog/blob/568e3f972614d4299d2aa00cb088be02b2e0325e/routers/api/v1/topic.go#L187)

如果可以，直接用curl 可以访问，或者根据 [项目README.md](https://github.com/sun-wenming/gin-blog)
 ```
curl -X PUT "http://localhost:8000/api/v1/topics/1" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"modified_by\": 1, \"name\": \"主题名称\", \"state\": 1}"
```

2. 入参是通过 `path 与 body` 
如: `http://localhost:8000/api/v1/topics/1`
body字段为 topic ： 数据为：(可以根据 上述curl 或 swagger网址调用)
```
{
  "modified_by": 1,
  "name": "主题名称",
  "state": 1
}
```

3.  数据库初始化sql文件 [luoliluosuo.sql](https://github.com/sun-wenming/gin-blog/blob/master/luoliluosuo.sql)  数据库名称为  `luoliluosuo`  
在项目的conf配置文件下。数据库 用户 密码默认为 `root`

PS：我是根据  煎鱼大大的项目改造的练手demo。写了几天之后手抖多点了一次请求发现了这个问题。望可以帮助解决下。想知其所以然。谢谢。

**Comment by sun-wenming** [comment]
@liangyu422  我还未接触到此类型的知识，刚入门。  抱歉。

**Comment by EDDYCJY** [comment]
@sun-wenming 我认真看了你的代码，你在这块犯了一个低级错误，代码如下：

```
func EditTopic(id int, data interface{}) error {
	fmt.Println(db) //map[name:主题名称 modified_by:1]
	db = db.Model(&Topic{}).Where("id = ? ", id).Updates(data)
	err := db.Error
	logging.Info(err)
	if err != nil {
		return err
	}
	return nil
}
```

你想想有没有什么问题？

**Comment by EDDYCJY** [comment]
我看到你已经把 `db` 打印出来了，可能就差一步了。详细的分析如下：

**【问题】**

db 这一个变量，它是一个全局变量。而在这里。你把 db 链式又重新赋予给了 db。因此导致了 db 变量不断地叠加。这就是你这个 BUG 的问题所在。

---

你可以把代码改成这样，修改后的代码如下：

```
func EditTopic(id int, data interface{}) error {
	if err := db.Model(&Topic{}).Where("id = ? ", id).Updates(data).Error; err != nil {
		logging.Info(err)
		return err
	}
	return nil
}
```

有两个办法，第一是重新赋予变量，第二种就是不重复叠加赋值。两种方案都可以解决你的问题 😄

**Comment by sun-wenming** [comment]
谢谢您的指点。
之前专门写个方法查询数据库，判断此ID的数据是否存在，感觉多执行了一条sql语句，影响速度(菜鸟臆想)。
因此写了如下操作。
![image](https://user-images.githubusercontent.com/22268505/48978518-8ee0aa00-f0e7-11e8-9859-6fb16a7ebd9e.png)
导致习惯性的用一个变量接收返回的信息。没有意识到这是全局变量。犯了很低级错误。
感谢指导。

**Comment by EDDYCJY** [comment]
判断数据是否存在的话，看实际需求，合理的 SQL 都是没有问题的

**Comment by EDDYCJY** [comment]
没事，你有学到东西就好。欢迎随时有问题再反馈 👍

**Comment by liangyu422** [comment]
> 没事，你有学到东西就好。欢迎随时有问题再反馈 👍

好热心的人

**Comment by sun-wenming** [comment]
@EDDYCJY   您好，我发现了同样的问题在此库中。[GetTags()  db重新赋值](https://github.com/EDDYCJY/go-gin-example/blob/8e115e022403cc956fda2eb63712147d67346388/models/tag.go#L43)

另外 如果 `pageNum>0`时，
导致`http://localhost:8000/api/v1/tags?page=1` 查找不到前十条数据。
原因：[page=1将导致 result 一直为0](https://github.com/EDDYCJY/go-gin-example/blob/8e115e022403cc956fda2eb63712147d67346388/pkg/util/pagination.go#L14)
因此我做了如下修改：
```
func GetTags(pageNum int, pageSize int, maps interface{}) ([]Tag, error) {
	var (
		tags []Tag
		err  error
	)
	if pageSize > 0 && pageNum >= 0 {
		err = db.Offset(pageNum).Limit(pageSize).Where(maps).Find(&tags).Error
	} else {
		err = db.Where(maps).Find(&tags).Error
	}
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}
	return tags, nil
}
```

**Comment by EDDYCJY** [comment]
@sun-wenming 已修改，感谢反馈 👍
