### ISSUE TITLE
swaggo 的BasePath是不是应该修改一下?

### ISSUE THREAD

**Issue by y1281010069** [EDDYCJY/go-gin-example#2]
main.go 22行的BasePath填 ‘/’ 会不会比较好，
不然在swagger/index.html页面的里面测试测口的时候地址是
http://127.0.0.1:8000/v1/api/v1/articles?tag_id=1,
有两个v1

**Comment by EDDYCJY** [comment]
不好意思，回复晚了

已修复该问题（[e1073af9be2cc91e3977f7c8fff05508063cdf1b](https://github.com/EDDYCJY/go-gin-example/commit/e1073af9be2cc91e3977f7c8fff05508063cdf1b)）
