### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by weihuahuang** [EDDYCJY/go-gin-example#20]
package golang.org/x/image/math/fixed: unrecognized import path "golang.org/x/image/math/fixed" (https fetch: Get https://golang.org/x/image/math/fixed?go-get=1: dial tcp 216.239.3
7.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host
 has failed to respond.)
package golang.org/x/image/font: unrecognized import path "golang.org/x/image/font" (https fetch: Get https://golang.org/x/image/font?go-get=1: dial tcp 216.239.37.1:443: connectex
: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to res
pond.)

**Comment by EDDYCJY** [comment]
缺少的第三方依赖包已重新添加到 vendor/ 中，现在应该可以了。麻烦你重新拉取一下

```
$ go get -u github.com/EDDYCJY/go-gin-example
```

**Comment by EDDYCJY** [comment]
@weihuahuang 你是 windows 系统？

**Comment by weihuahuang** [comment]
是的

**Comment by EDDYCJY** [comment]
@weihuahuang  Windows 的话，把这块代码放出来：https://github.com/EDDYCJY/go-gin-example/blob/master/main.go#L39-L48 

平滑重启这块的代码 Windows 不支持，因此要注释掉：https://github.com/EDDYCJY/go-gin-example/blob/master/main.go#L51-L62

**Comment by EDDYCJY** [comment]
@weihuahuang 你环境上 `runtime.GOOS` 输出出来的值是什么呢？

**Comment by weihua2018** [comment]
删除了项目，重新拉取的时候报错。
D:\server\gopath>go get github.com/EDDYCJY/go-gin-example
# github.com/EDDYCJY/go-gin-example/vendor/github.com/fvbock/endless
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:64:3: undefined: syscall.SIGUSR1
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:65:3: undefined: syscall.SIGUSR2
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:68:3: undefined: syscall.SIGTSTP
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:111:5: undefined: syscall.SIGUSR1
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:112:5: undefined: syscall.SIGUSR2
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:115:5: undefined: syscall.SIGTSTP
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:119:5: undefined: syscall.SIGUSR1
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:120:5: undefined: syscall.SIGUSR2
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:123:5: undefined: syscall.SIGTSTP
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:224:3: undefined: syscall.Kill
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:224:3: too many errors

D:\server\gopath>
D:\server\gopath>
D:\server\gopath>
D:\server\gopath>
D:\server\gopath>
D:\server\gopath>go get github.com/EDDYCJY/go-gin-example
# github.com/EDDYCJY/go-gin-example/vendor/github.com/fvbock/endless
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:64:3: undefined: syscall.SIGUSR1
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:65:3: undefined: syscall.SIGUSR2
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:68:3: undefined: syscall.SIGTSTP
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:111:5: undefined: syscall.SIGUSR1
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:112:5: undefined: syscall.SIGUSR2
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:115:5: undefined: syscall.SIGTSTP
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:119:5: undefined: syscall.SIGUSR1
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:120:5: undefined: syscall.SIGUSR2
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:123:5: undefined: syscall.SIGTSTP
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:224:3: undefined: syscall.Kill
src\github.com\EDDYCJY\go-gin-example\vendor\github.com\fvbock\endless\endless.go:224:3: too many errors

**Comment by EDDYCJY** [comment]
@weihua2018 你应该

```
$ go get -u github.com/EDDYCJY/go-gin-example
```

**Comment by EDDYCJY** [comment]
另外如果你是 windows 系统的话，应该把如下代码**打开**注释：https://github.com/EDDYCJY/go-gin-example/blob/master/main.go#L36-L46

把 endless 的相关代码给注释了：https://github.com/EDDYCJY/go-gin-example/blob/master/main.go#L48-L59
