### ISSUE TITLE
希望能有一些前端的实现就好了

### ISSUE THREAD

**Issue by airystar** [EDDYCJY/go-gin-example#22]
这个框架及教程很棒，但我对后端和前端如何进行交互不太清楚，比如后端怎么从前端取数据及提供数据给前端，如能增加一些前端的实例页面就好了

**Comment by EDDYCJY** [comment]
感谢支持。前端实现的话目前没有计划，这块不是这个项目的初衷

而对于前端和后端的交互这块，网上有很多资料可以了解。这个项目包含了许多 API，显然前端是通过 HTTP/1.1 请求到服务端的接口，服务端再响应返回结果集的
