### ISSUE TITLE
BlogAPIs-02.md 测试时发现有bug

### ISSUE THREAD

**Issue by kakaok** [EDDYCJY/go-gin-example#23]
在go1.9.1下测试BlogAPIs-02.md中的代码 发现有问题  
![image](https://user-images.githubusercontent.com/10599857/49264451-3d3e7380-f489-11e8-9b77-94f92719374b.png)

**Comment by EDDYCJY** [comment]
@kakaok 可能你需要提供重现的场景

- 调用了什么接口？
- 调用接口的入参是什么？
- 出问题的那段代码是怎么样的？

否则我无法保证你与我的代码是一致的，另外我也重现不了你的问题...

**Comment by kakaok** [comment]
[gin-blog.zip](https://github.com/EDDYCJY/go-gin-example/files/2642137/gin-blog.zip)

这是当时的文件，数据库只有一个账号数据 其它的都是按照BlogAPIs-02.md 来的

**Comment by EDDYCJY** [comment]
我简单看了一下你发我的该次代码，这次的代码显然是有问题的。但既然你是按照博文的来，应该在某些写法上严格遵守。建议仔细排查你的代码哦 🤔

在 models/models.go 中，你发的版本是：

```
....
db, err := gorm.Open(dbType, fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local", user,
		password,
		host,
		dbName))
...
```

该我在博文中，写法是：

```
...
    db, err = gorm.Open(dbType, fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8&parseTime=True&loc=Local", 
        user, 
        password, 
        host, 
        dbName))
...
```

建议以 [博文代码](https://github.com/EDDYCJY/blog/blob/master/golang/gin/2018-02-16-Gin%E5%AE%9E%E8%B7%B5-%E8%BF%9E%E8%BD%BD%E4%BA%8C-%E6%90%AD%E5%BB%BABlogAPIs-01.md#%E7%BC%96%E5%86%99models-init
) 或 [go-gin-example](https://github.com/EDDYCJY/go-gin-example/blob/master/models/models.go#L25) 项目的最新示例代码为基准，避免不必要的问题
