### ISSUE TITLE
预加载Scan指定struct类不执行预加载表.对于预加载和Scan结合有没有好的办法呢？

### ISSUE THREAD

**Issue by sun-wenming** [EDDYCJY/go-gin-example#24]
又来麻烦了,尴尬学艺不精.
开始按照 [gorm:Issues1965](https://github.com/jinzhu/gorm/issues/1965)实现了接近的效果.
半月前也提了一个Issues但似乎无人知晓解答.
看下源码心想在  Scan之前执行,Find将值全部查到. `s.value` Set 就会有tag表的数据,可还是不可以.
![image](https://user-images.githubusercontent.com/22268505/49268885-10945700-f49d-11e8-8b81-ae8250b04eb5.png)
如果有时间麻烦帮忙救救强迫症.(去掉strcut中无用的字段)
```
	var topics []*MResult
	var topics2 []*Topic
	err := db.Select("id,name").Preload("Tags", func(db *gorm.DB) *gorm.DB {
		return db.Select("id,name,tag.topic_id")
	}).Where(maps).Find(&topics2).Scan(&topics).Error
```
我目前实现的是：
(查询结果：结构有些臃肿，想要的效果是只显示select中的内容(红箭头指向的))
[gorm 查询语句](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/models/topic.go#L56)
```
        // err := db.Select("id,name").Preload("Tags", func(db *gorm.DB) *gorm.DB {
	// 	return db.Select("id,name,tag.topic_id")
	// }).Where(maps).Find(&topics).Error
```
![结果](https://user-images.githubusercontent.com/22268505/49267726-c9a36300-f496-11e8-981b-fd79a44b6735.png)

在网上查找是用[Scan](http://gorm.book.jasperxu.com/crud.html#1222-scan-) 解决.
但是不执行查询tag表语句了.  关联效果好像因为[新的`struct`类](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/models/topic.go#L42)失效了.

[gorm 查询语句](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/models/topic.go#L59)
```
	err := db.Select("id,name").Model(&Topic{}).Select("id,name").Preload("Tags", func(db *gorm.DB) *gorm.DB {
		return db.Select("id,name,tag.topic_id")
	}).Where(maps).Scan(&topics).Error
```
**查询结果**
![image](https://user-images.githubusercontent.com/22268505/49267940-c197f300-f497-11e8-9006-31197d583cd5.png)

### 重现步骤
1. 重新pull下,将数据库数据更新下.[sql文件](https://github.com/sun-wenming/gin-blog/blob/master/luoliluosuo.sql)
2. 涉及到的方法入口. 
[routers/api/v1/topic.go](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/routers/api/v1/topic.go#L68)  -> [service/topic_service/topic.go](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/service/topic_service/topic.go#L74) -> [models/topic.go->GetTopics()](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/models/topic.go#L49)

3. 测试 
[切换 models/topic.go->GetTopics() 返回值 为 []*Topic ](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/models/topic.go#L49)

[切换 service/topic_service/topic.go->GetAll() 返回值为 []*models.Topic ](https://github.com/sun-wenming/gin-blog/blob/48986d057873252bc844cb9b0a846d07a680e262/service/topic_service/topic.go#L52)

运行打开 http://localhost:8000/swagger/index.html  
执行 获取主题列表 
或者 利用 `curl`
`curl -X GET "http://localhost:8000/api/v1/topics" -H "accept: application/json"`

Thx.

**Comment by EDDYCJY** [comment]
我认真看了你的描述，其实你是想最终实现无用（零值）的字段不输出到结果集上，对吗？

你可以通过这样子修改，达到目的：

```
type Model struct {
	ID         int `gorm:"primary_key" json:"id,omitempty"`
	CreatedOn  int `json:"created_on,omitempty"`
	ModifiedOn int `json:"modified_on,omitempty"`
	DeletedOn  int `json:"deleted_on,omitempty"`
}

....

type Article struct {
	Model

	TagID int `json:"tag_id,omitempty" gorm:"index"`
	Tag   Tag `json:"tag"`

	Title         string `json:"title,omitempty"`
	Desc          string `json:"desc,omitempty"`
	Content       string `json:"content,omitempty"`
	CoverImageUrl string `json:"cover_image_url,omitempty"`
	CreatedBy     string `json:"created_by,omitempty"`
	ModifiedBy    string `json:"modified_by,omitempty"`
	State         int    `json:"state,omitempty"`
}
```

对 json 字面量添加 `omitempty` 标识符。这样子的话，接口输出的结果集就不会包含零值啦！😄

**Comment by EDDYCJY** [comment]
另外如果你是想说，要求 Select 到什么字段，T Struct 就只展示什么字段，没有取的不展示的话。
我觉得不谈场景的话，这样子有些吹毛求疵，没有太大必要。硬要说的话，我甚至可以认为你只取 2 个字段和取全部字段，他们并不是一个实体。

因此我认为没有太大必要纠结这个，因为在绝大多数的场景下都是没有实质影响的~

**Comment by sun-wenming** [comment]
非常感谢，帮了很大的忙。
一开始按照gorm的文档[Scan](http://gorm.book.jasperxu.com/crud.html#1222-scan-)的方向就错了。。一个接口需求创建一个实体类的操作**不可取。**

根据你的提示，查找[Golang的json文档做法更合理](https://golang.org/pkg/encoding/json/#Marshal)
这样也能达到目的，移动开发的人不会再抱怨：
  **"我只要`id`和`name` 两个字段，你给我返回十几个字段，这让咋搞~"** 

(PS：我目前在做移动开发努力转Go中。要是后台给我返回这么多无用数据，我要崩溃了)

有事没事还是多看[Golang关键性文档。](https://golang.org/pkg/)，少打游戏 🎮 。有生之年遇见大佬，真好。 😄

**Comment by EDDYCJY** [comment]
@sun-wenming  不客气，加油！

**Comment by cw4t** [comment]
我也遇到这个问题，请问怎么解决呢
