### ISSUE TITLE
关于go项目结构的问题

### ISSUE THREAD

**Issue by 1011875777** [EDDYCJY/go-gin-example#25]
在response.go中第15行代码 "code": httpCode, 此处应该"code": errCode更合理吧！

另外还有个疑问：
    为什么不把service中的方法直接封装到model中为结构方法，v1/api目录相当于controller, 这样在v1/api中直接调用model的方法不是更好吗？ 
    我看到你在service里面从新定义了结构，和对应model类似，作用仅仅只是用来接收v1/api传递下来的参数， 那为什么不直接用model呢，如果service里面定义的struct意图是用于逻辑数据模型，完全可以创建一个vo目录，里面放逻辑层的model，比如UserVo.go，  因为我在看service代码时发现，struct既用来接收controller的参数，也用于返回给用户的数据模型，这样感觉有一点杂乱，这里只是个人见解，希望和你交流一下。

**Comment by EDDYCJY** [comment]
service 与 model struct 的问题，具体可以参见 https://github.com/EDDYCJY/go-gin-example/issues/9#issuecomment-397862332。我在其他 issue 回答过这个问题

**Comment by EDDYCJY** [comment]
“在response.go中第15行代码 "code": httpCode, 此处应该"code": errCode更合理吧！”

```
g.C.JSON(httpCode, gin.H{
		"code": httpCode,
		"msg":  e.GetMsg(errCode),
		"data": data,
	})
```

在实际代码中，我们的 code 实际代指 httpCode，是它的具体声明。而 errCode 更像是抽象在 httpCode 上的理念。我们是利用了 httpCode 来作为 errCode。

因此我认为两个命名都行。不同角度看法罢了

**Comment by EDDYCJY** [comment]
@1011875777 hello?

**Comment by 1011875777** [comment]
我觉得你这个比较繁琐，为什么不直接去掉service，然后直接在v1下的handle里面完成逻辑调用model，所有与model相关的外部调用方法都封装为结构方法，一些内部需要的逻辑用普通函数完成； 你之前应该有做过java，java的架构一般都是controller-》service-》dao 等等，但是go语言足够简洁，既可以面向对象也可以面向过程，没必要像java这样分得太细； 

还有这个应该是g.C.JSON(httpCode, gin.H{
		"code": errCode,
		"msg":  e.GetMsg(errCode),
		"data": data,
	})  不是说你的res结构有问题，应该是你失误写错了，你把code也赋值为httpCode，这个本来是业务状态码，结果所有值都是=200，这样的话code没什么意义。
@EDDYCJY
