### ISSUE TITLE
断点调试时只有第一次请求进入，第二次不管是其它url都只输入请求日志。不进入断点

### ISSUE THREAD

**Issue by winsonink** [EDDYCJY/go-gin-example#26]
你请，请问一下，我设置断点看下整个流程和函数的执行。只有启动第一次是入断点的，第二次刷新请求控制台只输入请求日志的信息，却不进去断点，我用的goland以为是ide的问题，切换到另一个项目(不是gin)是正常的。每次请求的日志都是正常打印的。
<img width="1270" alt="qq20181207-234203 2x" src="https://user-images.githubusercontent.com/20497641/49657281-4aa3c100-fa7a-11e8-93c2-493a15197a4c.png">

**Comment by winsonink** [comment]
但是调用auth这个api每次都可以进入断点
http://127.0.0.1:8000/auth?username=test&password=test123456
而api/v1/下所有的api请求只有程序启动时第一次是可以进入断点的，第二次刷新或者变更其它/api下的url都无法进入断点
我的man方法放口设置了很我断点，应该不存在断点设置的问题

**Comment by EDDYCJY** [comment]
既然都打断点了。你应当可以从本地环境仔细观察得出结果的，来提问反而有些舍近求远了

我没有直接对 main 函数打断点的习惯，建议直接对想要观察的方法集进行断点

另外 go-gin-example 能够正常提供服务，并且正常输出请求日志和响应结果。也正正说明了你的断点打的有问题，或是你观察有问题

我是这么认为的，建议你仔细看看

**Comment by EDDYCJY** [comment]
锤子其实就在你的手上，加油。

**Comment by EDDYCJY** [comment]
@winsonink 你把 JWT 的部分去掉了就可以话，那么比较常见的问题，就是你在调用需要鉴权的接口的时候，压根没有传 token 或者传错了...
