### ISSUE TITLE
win下的 endless 中的 signal 信号没有 syscall.SIGUSR1 和 syscall.SIGUSR2

### ISSUE THREAD

**Issue by NoSugarCoffee** [EDDYCJY/go-gin-example#28]
vendor\github.com\fvbock\endless\endless.go:64:3: undefined: syscall.SIGUSR1
vendor\github.com\fvbock\endless\endless.go:65:3: undefined: syscall.SIGUSR2
vendor\github.com\fvbock\endless\endless.go:68:3: undefined: syscall.SIGTSTP
vendor\github.com\fvbock\endless\endless.go:111:5: undefined: syscall.SIGUSR1
vendor\github.com\fvbock\endless\endless.go:112:5: undefined: syscall.SIGUSR2
vendor\github.com\fvbock\endless\endless.go:115:5: undefined: syscall.SIGTSTP
vendor\github.com\fvbock\endless\endless.go:119:5: undefined: syscall.SIGUSR1
vendor\github.com\fvbock\endless\endless.go:120:5: undefined: syscall.SIGUSR2
vendor\github.com\fvbock\endless\endless.go:123:5: undefined: syscall.SIGTSTP

**Comment by EDDYCJY** [comment]
另外如果你是 windows 系统的话，应该把如下代码打开注释：https://github.com/EDDYCJY/go-gin-example/blob/master/main.go#L36-L46

把 endless 的相关代码给注释了：https://github.com/EDDYCJY/go-gin-example/blob/master/main.go#L48-L59

**Comment by EDDYCJY** [comment]
这块我后面做个兼容吧。看来用 windows 的用户还是挺多的...

**Comment by EDDYCJY** [comment]
最终还是决定利用 net/http 默认支持 windows，因此将 endless 作为用户自己的在 Unix 系统下的可选方案
