### ISSUE TITLE
安装 gin-swagegr 出现的问题

### ISSUE THREAD

**Issue by VICTORYGS** [EDDYCJY/go-gin-example#29]
![image](https://user-images.githubusercontent.com/33747619/50322113-c2f49280-050e-11e9-9e87-f3d5c3a6e328.png)
有大佬知道怎么解决吗

**Comment by EDDYCJY** [comment]
@VICTORYGS 只需删除这些目录，再重新执行，就能够被正确拉下来了。可能是你先前拉取的有问题
（拉取 gin-swagger 的时候，注意要全局翻墙）

**Comment by VICTORYGS** [comment]
![image](https://user-images.githubusercontent.com/33747619/50326024-ef1a0e80-0522-11e9-8305-2d497e8bf281.png)
![image](https://user-images.githubusercontent.com/33747619/50326030-fb05d080-0522-11e9-9372-4f36a39285ed.png)

原来用gopm 下载 会帮我安装 golang.org 等包 文件, 现在我删掉之前下的包 为什么就不会重新帮我下载这些包了呢?

**Comment by EDDYCJY** [comment]
应该是 gopm 帮你缓存了临时文件，建议清理执行如下命令清理：

```
$ gopm clean
```

或者删除缓存目录 `$USER/.gopm/repos`。我是建议你上梯子后全局翻墙
进行拉取的，因为 `gin-swagger` 涉及了不少墙外的包...

**Comment by VICTORYGS** [comment]
大哥 你知道window 下 有什么翻墙软件吗

**Comment by EDDYCJY** [comment]
翻车软件的话可以使用 [shadowsocks](https://github.com/shadowsocks/shadowsocks-windows/releases)

**Comment by VICTORYGS** [comment]
![image](https://user-images.githubusercontent.com/33747619/50382517-49120400-06dc-11e9-814a-33834028f4e5.png)
已经翻墙了,但还是会这样.....😭

**Comment by EDDYCJY** [comment]
@VICTORYGS 老铁，你认真仔细的看看错误提示。它都提示你

“连接尝试失败，因为连接方在一段时间后没有正确响应，或者建立的连接失败，因为连接的主机无法响应了”

显然你没有成功翻墙 😅

**Comment by VICTORYGS** [comment]
我知道问题在哪里了 谢谢 大佬的帮助
![image](https://user-images.githubusercontent.com/33747619/50389174-b3b95300-0761-11e9-9d11-9382249a6c33.png)

**Comment by VICTORYGS** [comment]
swag init 之后已经生成文件了  里面也有相应的路由信息  
但是打开http://127.0.0.1:8000/swagger/index.html  还是不能显示出信息 不知道怎么回事...
![image](https://user-images.githubusercontent.com/33747619/50389687-3e9d4c00-0768-11e9-9c4b-c1e3047861e3.png)

**Comment by EDDYCJY** [comment]
@VICTORYGS 有对接口写注解吗？可以对比下样例的代码注解

**Comment by EDDYCJY** [comment]
@VICTORYGS 建议你重新检查一下生成、部署步骤，这种错误提示基本都是配置相关的问题...

**Comment by EDDYCJY** [comment]
@VICTORYGS 若有其他问题，请提一个维度更准确的 issue。目前这个 issue 涉及好几个问题了，因此关闭
