### ISSUE TITLE
ok, _ := valid.Valid(&a)

### ISSUE THREAD

**Issue by xhochipe** [EDDYCJY/go-gin-example#3]
routers里面验证用户名密码，这样验证会存在问题的，加入我用户名密码为空呢

**Comment by EDDYCJY** [comment]
- Request: HTTP GET -> http://127.0.0.01:8000/auth?username=&password=

- Response: 

```
{
    "code": 400,
    "data": {},
    "msg": "请求参数错误"
}
```

@xhochipe 你是指假设这个密钥设定的 username 和 password 就空字符串为正确的情况？？

这点可以明确告诉你，生产环境下不存在

真正做这块逻辑是不允许留空的，一般是加密加盐的密钥，并且要求有一定的复杂度，防止爆破
