### ISSUE TITLE
redis 缓存与数据库更新的过期机制

### ISSUE THREAD

**Issue by xguox** [EDDYCJY/go-gin-example#30]
看到比如 package article_service 里边的, 查了 Article 单个或列表都会去设置 redis 缓存, 类似:

```go
gredis.Set(key, article, 3600)

gredis.Set(key, articles, 3600)
```

但是, 没有看到哪里有过期, 是只能靠这个 3600s 吗? 如果数据库更新了某个 Article 的话, 取到的是不是就是旧的数据而不是数据库最新的数据?

**Comment by EDDYCJY** [comment]
显然，如果是真实的业务项目。你应该还有个业务后台，在 新增/变更 标签或文章的时候，会清空缓存或者重载缓存....

**Comment by yiippee** [comment]
“显然，如果是真实的业务项目。你应该还有个业务后台，在 新增/变更 标签或文章的时候，会清空缓存或者重载缓存....”   感觉这个可以在 service 层做吗？ 你说的这个业务后台大概是什么样子的呢？ 能够举一个例子呢？谢谢啊。
