### ISSUE TITLE
热更新之优雅的停止程序同时如何启动新的程序监听新请求?

### ISSUE THREAD

**Issue by sun-wenming** [EDDYCJY/go-gin-example#31]
您好：
    我使用[Shutdown](https://github.com/EDDYCJY/blog/blob/master/golang/gin/2018-03-15-Gin%E5%AE%9E%E8%B7%B5-%E8%BF%9E%E8%BD%BD%E4%B8%83-Golang%E4%BC%98%E9%9B%85%E9%87%8D%E5%90%AFHTTP%E6%9C%8D%E5%8A%A1.md#httpserver---shutdown)方法来实现热更新。当我发出信号之后即：SIGINT(ctrl+C)之后，可以正常等待正在请求的接口陆续请求完成。但是我该如何同时启动新的应用程序，来接收一些新的请求呢？

问题：正在运行的二进制文件无法覆盖，fock新进程有出现所说的[守护进程问题](https://github.com/EDDYCJY/blog/blob/master/golang/gin/2018-03-15-Gin%E5%AE%9E%E8%B7%B5-%E8%BF%9E%E8%BD%BD%E4%B8%83-Golang%E4%BC%98%E9%9B%85%E9%87%8D%E5%90%AFHTTP%E6%9C%8D%E5%8A%A1.md#%E9%97%AE%E9%A2%98)。我该如何开启一个覆盖老的端口和二进制文件来监听新的接口请求呢？目前只完成了优雅得到停止，但是没有启动起来。从其他目录运行文件`./main`会提示端口被占用，导致新应用程序无法启动。

希望有时间可以透露下您的解决方案。看文章之前无接触过热更新，百度也无找到答案。谢谢您。

**Comment by EDDYCJY** [comment]
@sun-wenming 抱歉晚回复了，最近病得一塌糊。因此先前都没有回复你

---

首先，你在这里提到的是执行 “SIGINT(ctrl+c)” ，也就是执行了信号 SIGINT，指令的作用是终止当前的命令或脚本（kill + 9 可以认为也是类似的效果）。显然我文章建议使用的是 `kill -1 pid`

接下来，要认清楚 “热更新” 这一个概念，你优雅的停止了它，实际上是一共有 2 个进程。一个老进程，一个新进程，老的在处理原有的逻辑后。新的已经开始顶替它原有的端口监听了。那你又再运行 `./main` 当然会提示端口被占用....

在最后，我觉得你想问的生产环境的是 “热升级” 吧。在实际的生产环境中，我们会采取更细腻的方式。而不是用这种侵入式的。我们在 K8S 中会有 2 个 Docker （互备），当进行升级的时候，会先替换掉其中一个  Docker。再将流量导入过去。再更替另外一个....

当然在生产环境用处不止这么点，你应该是想问的这类

**Comment by sun-wenming** [comment]
谢谢您的解答。首先天气越来越不好了，注意身体，最近身边好多人也生病了。

---

最近在网上找的利用父子进程操作实现的。想要细腻的实现，展开实现需要更多的知识。
达到去面试工作的水准，再分配时间过多攻略。

PS：最近在学习微服务。用到了Docker，是个强大的工具.

**Comment by EDDYCJY** [comment]
其实这个 issue 涉及了两大块知识区域，一个是父子进程的问题，另外一个是 K8S 体系下的 Docker 热备（互备）的体系问题

面试的话，建议至少先理解一下其**工作模式**。深入的话，看你自己择日学习 😄
