### ISSUE TITLE
timeout的设置问题

### ISSUE THREAD

**Issue by VICTORYGS** [EDDYCJY/go-gin-example#32]
![image](https://user-images.githubusercontent.com/33747619/51101071-068fa300-1814-11e9-9fd7-11a57105ac63.png)
![image](https://user-images.githubusercontent.com/33747619/51101195-a0efe680-1814-11e9-973b-1585afd9646c.png)
dear 老哥:
为什么我超时时间 设置15, 请求数据的时候就返回不了数据呢? 这不是15吗?

**Comment by EDDYCJY** [comment]
抱歉，最近生病回复晚了

---

你指的是 setting.go 文件的代码，如下：

```
...
ServerSetting.ReadTimeout = ServerSetting.ReadTimeout * time.Second
ServerSetting.WriteTimeout = ServerSetting.ReadTimeout * time.Second
....
```

关于 “如果把这两行删掉会出现什么问题”。最好的学习就是自己动手去做，我建议你自己实操一遍

假设删除这两行，会导致它所设置的 Timeout 时间会非常非常非常非常非常短，结果就是响应时间等待时间太短，你的接口几乎都会出问题...
