### ISSUE TITLE
咨询下go build后不会把配置文件打包吗？

### ISSUE THREAD

**Issue by junruyi** [EDDYCJY/go-gin-example#35]
![image](https://user-images.githubusercontent.com/28618485/51468134-2b9e8b80-1da9-11e9-9e69-13ff186a34e9.png)
把build 后exe放到GOPATH目录是可以执行，但放到其它地方就提示找不到文件了

**Comment by EDDYCJY** [comment]
@junruyi 不会的，Go 的编译是不会把配置文件打包到二进制文件里面的哦。

**Comment by junruyi** [comment]
好的，谢谢~~

**Comment by EDDYCJY** [comment]
@junruyi 你可以看看这篇文章，应该会对你有所帮助。传送门：[聊一聊，Golang相对路径问题](https://github.com/EDDYCJY/blog/blob/master/golang/2018-03-13-%E8%81%8A%E4%B8%80%E8%81%8A%EF%BC%8CGolang%E7%9B%B8%E5%AF%B9%E8%B7%AF%E5%BE%84%E9%97%AE%E9%A2%98.md)

**Comment by junruyi** [comment]
好的，谢谢~



junruyi12@gmail.com
 
发件人： 煎鱼
发送时间： 2019-01-21 20:55
收件人： EDDYCJY/go-gin-example
抄送： junruyi; Mention
主题： Re: [EDDYCJY/go-gin-example] 咨询下go build后不会把配置文件打包吗？ (#35)
@junruyi 你可以看看这篇文章，应该会对你有所帮助。传送门：聊一聊，Golang相对路径问题
―
