### ISSUE TITLE
请问如果把请求方法都使用controller封装的话，在路由中需要怎么设置呢？

### ISSUE THREAD

**Issue by Stepkim** [EDDYCJY/go-gin-example#36]
![hellocontroller](https://user-images.githubusercontent.com/14869623/51664738-0e5dfd00-1ff5-11e9-8e5d-fca25882576a.png)

当我把方法放到controller中之后，在路由中设置会报错，说是参数类型不符合
![router](https://user-images.githubusercontent.com/14869623/51664859-6432a500-1ff5-11e9-9cb6-97fae2fa159a.png)

**Comment by EDDYCJY** [comment]
显然，看错误提示...它都已经告诉你类型不符合了，那你只需按规则实现它的类型要求就行了
我觉得没必要强套上 MVC 的想法，你可以参考下 beego 的实现
