### ISSUE TITLE
關於如何使用Transactions

### ISSUE THREAD

**Issue by nickbug** [EDDYCJY/go-gin-example#37]
請問在目前的架構下
DB transactions 這部分該如何應用呢?

**Comment by EDDYCJY** [comment]
@nickbug 你问的太泛了，请咨询更具体点？

你是指怎么使用事务？这块 gorm 的文档上有教哦...

**Comment by nickbug** [comment]
抱歉

假設以下場景(純粹為了使用Transaction舉的例子)
1. Article 於DB存放數量上限為10篇
2. 目前Article 於DB中存滿10篇

新增Article 的邏輯為以下
1. 新增 新 Article 
2. 刪除 舊 Article

那麼為了避免刪除舊Article時發生錯誤
導致存放數量上限超過10篇

這邊選擇使用了Transaction 來做錯誤rollback 或者正常commit

而gorm 提供的 Transaction 方法為
    tx = db.begin()

那在目前的架構下 model  是透過內部的 db 來操作
若直接進行替換內部 db 為 tx 感覺上不太適合的 

想請問您對此的看法

**Comment by EDDYCJY** [comment]
目前你指的内部 [db](https://github.com/EDDYCJY/go-gin-example/blob/master/models/models.go#L25)  这一个包全局变量，其实是个 Mysql 连接池

你所指的 “若直接進行替換內部 db 為 tx 感覺上不太適合的”。如果我理解没错的话，这个表述有问题吧。为何 内部 db 变量会被替换为 tx？

你执行了 `tx = db.begin()` 语句后，很有可能 gorm 只是去获取了一个数据库连接（句柄）使用罢了，他们俩其实是相对独立的。何来的 tx 替换 db 之说？

**Comment by nickbug** [comment]
會這樣說是因為
目前架構上若要進行DB操作
則是透過Model 內建立的 func 來進行
而 func 內部則是透過內部 db 變量來進行操作

若是要進行 transaction 
那勢必要建立一個 tx = db.begin 來獲得 transaction
但基於現行Model的寫法 這個 tx 該如何讓 Model使用呢?

Model 假定有兩個功能 新增文章、刪除文章
現在想要在一個 Transaction 內前後執行 新增、刪除的動作
那麼原本的新增、刪除功能
對於資料庫的操作就要用從 db 變成 tx 來進行

**Comment by EDDYCJY** [comment]
那就要改变写法了，因为这个例子是针对 gin 的。所以没有（编写）考虑你说的这种情况

实际你应该这么解决（最简单的解决办法），伪代码如下：

```
// DBEngine is a global vars for mysql connect.
var DBEngine *gorm.DB

// Define func
func GetArticle(db *gorm.DB, id int) (*Article, error) {
	...
}

func EditArticle(db *gorm.DB, id int, data interface{}) error {
	...
}

// Transaction
tx := DBEngine.Begin()

GetArticle(tx, ...)
EditArticle(tx, ...)

tx.Commit()
```

这样子就可以解决你的问题了

**Comment by EDDYCJY** [comment]
@nickbug 请问还有问题吗？

**Comment by nickbug** [comment]
沒了 感謝大神  新年快樂!

**Comment by EDDYCJY** [comment]
不客气，也祝你新年快乐！新的一年越来越 Go 😄
