### ISSUE TITLE
获取article接口返回的数据，tag_id字段和tag字段里的id值不一致

### ISSUE THREAD

**Issue by fubd** [EDDYCJY/go-gin-example#39]
{
"code": 200,
"msg": "ok",
"data": {
"id": 2,
"created_on": 0,
"modified_on": 0,
"deleted_on": 0,
"tag_id": 3,
"tag": {
  "id": 0,
  "created_on": 0,
  "modified_on": 0,
  "deleted_on": 0,
  "name": "",
  "created_by": "",
  "modified_by": "",
"state": 0
},
...

**Comment by fubd** [comment]
err := db.Where("id = ? AND deleted_on = ? ", id, 0).First(&article).Related(&article.Tag).Error

这里where查询id时，似乎同时查询了blog_tag和blog_article两张表的id。当tag_id和article id一致时，才会返回正确的tag数据。

**Comment by EDDYCJY** [comment]
@fubd 已修复，感谢反馈 ：）
