### ISSUE TITLE
运行代码无法加载app.ini

### ISSUE THREAD

**Issue by huangda2100** [EDDYCJY/go-gin-example#42]
setting.Setup, fail to parse 'conf/app.ini': open conf/app.ini: no such file or directory

**Comment by EDDYCJY** [comment]
@huangda2100 麻烦提供更多的信息，你这应该是本地操作的问题。因为配置文件是相对路径读取的..

如果你需要变更配置路径，是需要改配置的。否则默认的配置路径，就是在应用根目录下执行 `go run`

**Comment by EDDYCJY** [comment]
@huangda2100 还有问题吗？
