### ISSUE TITLE
怎样实现 热更新呢

### ISSUE THREAD

**Issue by VICTORYGS** [EDDYCJY/go-gin-example#43]
每次 改完gin的代码 都要自己重新go run 下,不太方便.
大佬知道怎样可以实现热更新吗?

**Comment by EDDYCJY** [comment]
你指的是 beego 的 bee 那种监听变更自动重启服务的工具吧，并不是传统的热更新啊。你可以通过 [fsnotify](https://github.com/howeyc/fsnotify) 去监听 gin 所属的文件内容。监听到有变更则结合自动重启就可以

---

我这边没怎么用过，主要是我编码习惯的问题，我都是先写好代码再阶段自测的~

**Comment by EDDYCJY** [comment]
@VICTORYGS 还有问题吗

**Comment by EDDYCJY** [comment]
@VICTORYGS 你可以用 https://github.com/codegangsta/gin ，能够比较好的解决你开发时的问题 ：）
