### ISSUE TITLE
几点疑惑及建议

### ISSUE THREAD

**Issue by canghai908** [EDDYCJY/go-gin-example#45]
几点建议：
1.Token获取应该使用post方式，Token验证应加在HTTP Header头部
2.Router的swagger注解有点问题，添加等POST接口应该使用body模式，直接添加
3.用户密码应该使用md5加密（看已经函数写了没用）

疑惑：
   1.业务错误代码调用有问题，已提交pr #46

**Comment by EDDYCJY** [comment]
1. Token 参数的获取和验证只是取值方式的不同，对于演示项目并没有实际性影响。如果真实使用，应当根据自己的实际情况进行修改或变更
2. Swagger 注解？你是指接口方法上面的注解吗。这里使用 object 是为了使用 `app.Response` 结构体展示。先前是用的 body，但因为要直接添加 `json` 字符串，容易太长且不人性化。因此不合适
3. 用户密码 MD5 加密，你是指 JWT 的时候吗？这块之前已经改了，可见 `util.GenerateToken` 方法
4. 业务错误码的问题，因为当时设计的时候。是考虑用 HTTP Code 作为 Status Code，业务错误码仅作为内部错误码交融使用（这块保留意见吧，如果要探讨实际使用。建议是根据实际项目决定，有放出来，也有只在内部记录的）

：） 感谢建议和反馈
