### ISSUE TITLE
大佬们好，我新手问个小疑惑，别笑我。。

### ISSUE THREAD

**Issue by gi19901212** [EDDYCJY/go-gin-example#47]
因为我是搞前端的，对后端的了解仅限于MVC，所以看到这个项目就开始找controller，没找到，发现业务逻辑好像是写在了routers/api目录下，这样做是基于什么考虑呢？是go框架的惯例吗。。。我内心有点不习惯，求解脱。。

**Comment by bencen** [comment]
你其实是可以分离出来的，后面我就分离了，项目大的话路由文件都要分离

**Comment by EDDYCJY** [comment]
......首先，后端不等于 MVC @gi19901212 

其次你要清楚地认识到项目的目录结构，是根据实际情况划分的。而你之前用一些后端框架，它是 MVC 框架。只是他采取的默认目录结构，也是因为 MVC **这一思想**广受认可和使用

而本项目中将 controller 改为了 routers/api，也只是一种写法罢了。也有一个原因，就是我不喜欢看到这个项目的人太过度套用 MVC 的思想。完全没有必要被此约束

最后有一句话很经典，约定大于配置
