### ISSUE TITLE
有个小小的疑惑，还往大佬们赐教

### ISSUE THREAD

**Issue by gi19901212** [EDDYCJY/go-gin-example#49]
首先感谢这个项目的作者，给了我入门学习go语言十分有效的帮助。
我的困惑就是关于“封装度”的问题，和我接触到的前端项目比起来呢，这个项目是倾向于把各种功能封装到函数，然后再调用的。
[举一处例子，比如在这里](https://github.com/EDDYCJY/go-gin-example/blob/master/service/article_service/article_poster.go#L143)
判断文件是否存在，用到了CheckMergedImage函数，但是这个函数其实就是把判断文件是否存在做了封装，那为何不把它封装的内容直接写到if语句后面呢，至少这样代码量看起来少了，而且阅读起来也不难。
这种处处皆函数的思想是一种设计模式，还是最佳实践，还是为了统一项目风格，或是作者的个人风格？
因为我个人刚接触这个，怕走弯路，所以想把代码之外的许多东西整明白。

**Comment by EDDYCJY** [comment]
@gi19901212 关于你的疑惑，我理解是你对于 “把各种功能封装到函数，然后再调用的” 这件事，不理解为什么要这么做，是吗？

首先，这个做法不分前后端，而是一个编码的工程化思想。我反问你，难道你做过的实际项目，都不进行封装的吗？把所有代码一把梭丢在一块？如果考虑到未来有重用可能性的，也不提前封装吗？

写代码应当是分层次的，也就是结构化。而不是写成一个大泥球

**Comment by EDDYCJY** [comment]
感谢对项目的支持，有啥建议或者问题欢迎随时沟通 ：）
