### ISSUE TITLE
JwtSecret无法加载

### ISSUE THREAD

**Issue by EnxZhou** [EDDYCJY/go-gin-example#50]
配置文件go-gin-example/conf/app.ini中，设定的“JwtSecret = 233”不起作用；
可能问题出在go-gin-example/pkg/util/jwt.go中，设定全局变量JwtSecret这一句。
`var jwtSecret = []byte(setting.AppSetting.JwtSecret)`

应该是因为golang中是先导入包，再执行main.go中的init()
原代码执行的顺序为：

1. jwtSecret作为util的全局变量导入main.go中，将setting.AppSetting.JwtSecret赋值给jwtSecret，此时setting.AppSetting.JwtSecret为空；

2. 再执行main.go中的init()，给setting.AppSetting.JwtSecret赋值为233，jwtSecret一直都没有赋值成功。

不知道是否是这样，望赐教。

**Comment by EDDYCJY** [comment]
@EnxZhou  感谢反馈，是我之前疏忽了
