### ISSUE TITLE
对目录有一点疑惑

### ISSUE THREAD

**Issue by SamHz** [EDDYCJY/go-gin-example#53]
为什么API要和Router放在一起？Models里面为什么要放查询方法？设计目的是？

**Comment by gi19901212** [comment]
哈哈，这个问题曾经UP主给我回答过（UP主，听起来有B站风格？），API放在哪里其实没有什么关系，当然我们可能受MVC思想影响比较大，导致我们认为业务代码必须放置在Controller里（只是惯性思维）。这里UP主放到了V1文件夹里，我猜是为了方便版本切换，况且如果你实在过不了心里那道坎，可以移植出去嘛。还有，Models里放置查询方法有什么问题吗？要不然放哪里？

**Comment by EDDYCJY** [comment]
@gi19901212 听完有自己的想法挺好的，举一反三，勤加思考可以更强 ：）

**Comment by EDDYCJY** [comment]
@SamHz 请问还有其他疑问吗
