### ISSUE TITLE
更新一下mysql的driver支持8.0以后的authentication

### ISSUE THREAD

**Issue by wakaryry** [EDDYCJY/go-gin-example#54]

**Comment by wakaryry** [comment]
对于MySQL8.0以及以后的，会出现 models.Setup err: this authentication plugin is not supported。
主要原因是MySQL8.0的默认认证方式/密码加密方式的变化。
更新mysql的driver就可以的。
如何更新？
作者用的是[govendor](https://github.com/kardianos/govendor)进行的包管理，如果我们还没有govendor这个东西，可以go get一下：
`go get -u github.com/kardianos/govendor`
这个时候我们可以在gopath下面的bin文件夹内看到govendor，可以用这个govendor来作为指令去更新 mysql的driver。

如何使用：
首先我们应该CD到project目录下，也就是go-gin-example下面；
然后运行：
`/gopath/bin/govendor fetch github.com/go-sql-driver/mysql`
这样就可以更新driver来支持8.0以后的mysql了。
你可以在go-gin-example下面的vendor文件夹内发现的确更新了这个driver。

然后对于新手来说，记住一点，我们go get下来的东西会出现在gopath下面的src下，指令在bin下面。
我就是新手，第一次接触go。
感觉心里很不舒服。因为我想自己随便放一个位置。不想放在这种指定的地方。

**Comment by EDDYCJY** [comment]
我这两天更新一下 vendor/ 下的 driver，感谢反馈 ：）

**Comment by EDDYCJY** [comment]
已修复，感谢。
