### ISSUE TITLE
对于service层的疑惑

### ISSUE THREAD

**Issue by rikioy** [EDDYCJY/go-gin-example#58]
我看多了一个service层，请问这个层的意义是怎样？吧对文章和标签等操作写在model里不好吗？

**Comment by rikioy** [comment]
仔细看了下。model层是对数据库表的封装，service是对实际对象的封装，是这个意思吗？

**Comment by wangxf1987** [comment]
model层是对数据库操作对逻辑封装，具有原子性，不要把过多的复杂逻辑放到model层；
service层是对数据库层更高的封装，这里可以加入更多的操作逻辑，联合不同模块的model以及不同功能serivce做更复杂的操作。
而不得不提router的api层，这一层会调用service，相对于api层，不需要知道service负责的逻辑，只需要按照需求，加入一些逻辑，即可完成对service的调用。

**Comment by EDDYCJY** [comment]
@wangxf1987 回答的差不多了，针对这个可以补充看下 https://github.com/EDDYCJY/go-gin-example/issues/9#issuecomment-397862332，效果更佳。
