### ISSUE TITLE
请问用的什么包管理工具？

### ISSUE THREAD

**Issue by Chalin-Shi** [EDDYCJY/go-gin-example#6]
如题。我用dep工具，无法初始化~~~还烦请帮忙看下~~~

**Comment by EDDYCJY** [comment]
这个项目使用的是 govendor 的依赖包管理工具

另外你是不需要再进行初始化的了，因为我使用 govendor 将项目所需的依赖包已经传到仓库（就是 vendor 目录里）了

所以你只需要直接运行即可 👍
