### ISSUE TITLE
求教，如何在model上注册 query的callbacks

### ISSUE THREAD

**Issue by lynnsoda** [EDDYCJY/go-gin-example#63]
大佬，有个细节需要您，您的go-gin-example里model在create update delete的时候注册了callbacks。那能不能在query的时候注册一个callbacks 呢，谢谢大佬
补充：比如存到数据库的是int形式的时间戳，或者常用的int形式status。查询后转成对于的时间字符串，status字符串。

**Comment by EDDYCJY** [comment]
@lynnsoda 可以的，有 Query callbacks 用法，详见 gorm 文档：http://gorm.io/docs/write_plugins.html#Register-callback-orders 或其代码：https://github.com/jinzhu/gorm/blob/master/callback_query.go。

**Comment by johnsonop** [comment]
@lynnsoda 您收到信息能给我一个联系方式吗, 找您有急事, 这是我的电话18215529528, qq:924235514@qq.com
