### ISSUE TITLE
go-ini 包路径更新

### ISSUE THREAD

**Issue by unknwon** [EDDYCJY/go-gin-example#66]
感谢使用 https://github.com/go-ini/ini ！

不过昨天开始这个包已经开始启用 Go Modules，所以导入路径只能规定成一个就是 `gopkg.in/ini.v1`。虽然旧版路径在未启用 Go Modules 的项目中依旧兼容（希望。。），但还是建议统一都修改成 `gopkg.in/ini.v1` 方便未来的读者 :D

**Comment by EDDYCJY** [comment]
@unknwon 收到，预计今晚（北京时间）修改 [go-gin-example](https://github.com/EDDYCJY/go-gin-example) 和 [Blog](https://github.com/EDDYCJY/blog) 文章内容。

这个提的好，的确刚刚已经有新读者的代码炸锅了在问我啥情况 😅

**Comment by unknwon** [comment]
roll back了。。一切照旧。。Happy coding! 不过建议还是早些改吧。。不然有一天v2还是要凉凉呀
