### ISSUE TITLE
一个package下有两个main

### ISSUE THREAD

**Issue by iosfxi** [EDDYCJY/go-gin-example#7]
你的仓库中 根目录下  main.go  和 cron.go 中都有main入口，导致 go get时  报错 
# github.com/EDDYCJY/go-gin-example
go/src/github.com/EDDYCJY/go-gin-example/main.go:21:6: main redeclared in this block
	previous declaration at go/src/github.com/EDDYCJY/go-gin-example/cron.go:12:6
go/src/github.com/EDDYCJY/go-gin-example/main.go:28:23: main.func1 redeclared in this block
	previous declaration at go/src/github.com/EDDYCJY/go-gin-example/cron.go:16:27

**Comment by EDDYCJY** [comment]
想着做为案例误传上去了，我现在清理一下
感谢反馈

**Comment by EDDYCJY** [comment]
已解决完毕（cron 在实际使用时在其他地方启动即可）

cron.go 的代码参考 https://segmentfault.com/a/1190000014666453 为准
