### ISSUE TITLE
请教一个问题，基于 gorm 如何进行 mysql 系统变量的查询

### ISSUE THREAD

**Issue by moooofly** [EDDYCJY/go-gin-example#70]
例如我想要完成如下查询

```
show global variables like 'read_only';
```

在 gorm 里面，没有找到用于 show 指令的操作~

**Comment by moooofly** [comment]
@EDDYCJY 求教

**Comment by EDDYCJY** [comment]
@moooofly 因为 ORM 比较偏向应用层的使用，这种需求的话，执行原生 SQL 的方式应该可以帮到你，例如： `db.Exec` 方法，具体你可以看看文档的[这一章节](https://gorm.io/docs/sql_builder.html#Run-Raw-SQL)。

**Comment by moooofly** [comment]
@EDDYCJY 多谢回复

我自己也尝试使用了 db.Raw 和 db.Exec 然后配合 Scan 来使用，然后发现，想要获取这种系统变量的值时，不知道如何定义作为 result 的 struct 

```
mysql> 
mysql> show global variables like 'read_only';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| read_only     | OFF   |
+---------------+-------+
1 row in set (0.01 sec)

mysql>
```

故怀疑仅仅基于 gorm 是不行的
