### ISSUE TITLE
线上如何部署

### ISSUE THREAD

**Issue by fivenull** [EDDYCJY/go-gin-example#72]
比如windows环境下，打包成exe文件后，还需要哪些文件？
linux环境下，打包成二进制后，如何后台运行，需要拷贝哪些文件去服务器？

**Comment by EDDYCJY** [comment]
如果是 Linux 环境下的话，你把应用编译成二进制文件后，你只需要将二进制文件和它所依赖的文件给拷贝去服务器就可以运行了。

如果你问的是具体如何部署使用，那就要配合负载均衡等等措施了。
