### ISSUE TITLE
关于硬删除！

### ISSUE THREAD

**Issue by seven1122** [EDDYCJY/go-gin-example#74]
大佬，从代码来看删除接口也是硬删除吧？为什么不用“Unscoped”？但是为什么在定时任务节你说“注意硬删除要使用 Unscoped()，这是 GORM 的约定”

**Comment by EDDYCJY** [comment]
在定时任务时，是讲解了有软删除这种做法，但你所说的业务接口写的是硬删，只是为了表现给你们看有这两种写法。
