### ISSUE TITLE
gitbook很多图片无法显示

### ISSUE THREAD

**Issue by Yvan7123** [EDDYCJY/go-gin-example#75]

**Comment by EDDYCJY** [comment]
@Yvan7123 因为之前的文章都是用的国外图床，你可以翻个墙看。或者直接跳到 Github 上面看，这样子他有封装一层图床，而国外图床的问题，我过段时间应该会写个脚本替换一下。

**Comment by EDDYCJY** [comment]
@Yvan7123 你把你那边有问题的页面具体发给我看看？

**Comment by Yvan7123** [comment]
@EDDYCJY  我同事的电脑能看。抱歉 应该是我电脑的原因 。感谢大佬

**Comment by Yvan7123** [comment]
链接是https://eddycjy.gitbook.io/golang/di-3-ke-gin/config-upload
开了vpn后就可以看到，已经在github上看完。感谢大佬的教程～

**Comment by EDDYCJY** [comment]
@Yvan7123 对你有所帮助就好，有什么问题欢迎随时交流。
