### ISSUE TITLE
关于代码中的结构体嵌套的优化

### ISSUE THREAD

**Issue by tgzl** [eddycjy/go-gin-example#76]
在models中的tag和article都包含一个
`BeforeCreate(scope *gorm.Scope) error 
 BeforeUpdate(scope *gorm.Scope) error
`
的方法,但是他们都有嵌套Model,所以可以根据go的特性,直接在Model中定义这两个方法
`
func (model *Model) BeforeCreate(scope *gorm.Scope) error
func (model *Model) BeforeUpdate(scope *gorm.Scope) error
`
这样可以简化代码,方便维护

**Comment by tgzl** [comment]
我读的https://book.eddycjy.com/golang/gin/api-03.html你写的笔记文档

**Comment by EDDYCJY** [comment]
@tgzl 提个 PR 上来看看如何？

**Comment by eddycjy** [comment]
@tgzl 你所提到的 callback 在 go-gin-example 项目中实际已经已 models 基类实现了 callback 了，传送门：https://github.com/eddycjy/go-gin-example/blob/master/models/models.go#L41-L43。

而文章这么提到只是为了表现标签和文章都是可以自己实现一套的而已。
