### ISSUE TITLE
key is of invalid type

### ISSUE THREAD

**Issue by kalifun** [EDDYCJY/go-gin-example#82]
获取密钥的时候报错key is of invalid type。
我根据查寻是这个地方出现了问题。
var jwtSecret = []byte(setting.JwtSecret)
获取jwtSecret的类型为[]uint8
获取setting.JwtSecret的类型为string，因为我们在setting.go中使用了MustString。
我很好奇，我们明明定义了类型为[]byte，但是最终的是[]uint8.
Token生成失败的原因应该就是这里，请帮忙解答一下谢谢。

**Comment by kalifun** [comment]
经过检查是自己这边的问题，谢谢。

**Comment by MaxsionLiu** [comment]
我也是同样的问题 能问下你那是啥问题吗 @kalifun
