### ISSUE TITLE
HTTP标准：auth 不该用 GET

### ISSUE THREAD

**Issue by sinkcup** [eddycjy/go-gin-example#83]
auth 应该用 POST，而不是 GET，不符合HTTP标准

https://github.com/EDDYCJY/go-gin-example/blob/a98c25f2172a74bcf9cd6272a7b0023480cdfa92/routers/api/auth.go#L27

**Comment by eddycjy** [comment]
@sinkcup  可理解，是否有具体的 HTTP 标准的传送门，让我基于此进行修改？

**Comment by sinkcup** [comment]
@eddycjy GET 是幂等的，文档：https://developer.mozilla.org/zh-CN/docs/Glossary/%E5%B9%82%E7%AD%89

**Comment by eddycjy** [comment]
@sinkcup OK，我会在近期对其进行修复，或者欢迎你进行 PR。

**Comment by sinkcup** [comment]
不客气，我最近不折腾 Go 了，因为没有企业级框架，做不了中型项目啊。https://sinkcup.github.io/go-frameworks

**Comment by eddycjy** [comment]
@sinkcup 感谢反馈，已调整。

**Comment by sinkcup** [comment]
@eddycjy 函数名还叫 GetAuth，文档也没改 https://github.com/eddycjy/go-gin-example/blame/master/README.md#L59
