### ISSUE TITLE
怎么才能在注解的app.Response的data中添加结构体呢？

### ISSUE THREAD

**Issue by jony-lee** [eddycjy/go-gin-example#85]
注解中返回的对象是app.Response，包含了code、msg、data，我想在data中包含详细的结构体应该怎么做呢？
![image](https://user-images.githubusercontent.com/43266490/67223981-db9d4400-f462-11e9-807c-8f294643e398.png)
这个结果我是通过把data中的数据类型改成了对应的结构体，不过我有很多这样的返回类型，不希望每一个返回类型都建立一个相应的Respose去做自动生成

**Comment by wizizm** [comment]
同问，go的swagger集成感觉不完善

**Comment by huangxingx** [comment]
这个问题 之前也是思考了很久, 但是一直解决不了, 最终放弃了

**Comment by eddycjy** [comment]
@jony-lee @wizizm @huangxingx  需要另外定义一个新的结构体（也就是你说的包含 code、msg、data）来用于 Swagger 展示，这个 gin-swagger 官方有进行特意说明。
