### ISSUE TITLE
Swagger有误

### ISSUE THREAD

**Issue by zyeking** [eddycjy/go-gin-example#88]
在go version go1.12.9 windows/amd64、swag version v1.6.3的环境下使用swag init会报错：ParseComment error in file routers\api\v1\article.go :can not find schema type: "v1.json"，查询了相关的文章后应该将// @Success 200  {string} json "{"code":200,"data":{},"msg":"ok"}"修改为// @Success 200  {string} string "{"code":200,"data":{},"msg":"ok"}"

**Comment by stevenlee87** [comment]
是这样的。遇到了同样的问题

**Comment by lyr1994** [comment]
The same error occur to me.

**Comment by lpzhi** [comment]
url := ginSwagger.URL("http://localhost:8090/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

这么使用 就可以

**Comment by eddycjy** [comment]
@zyeking @lpzhi @lyr1994  都是 swag v1.6.3 版本吗？

**Comment by eddycjy** [comment]
- version: swag version v1.6.3.
- err: 
```
ParseComment error in file routers\api\v1\article.go :can not find schema type: "v1.json"
```

@easonlin404 What component version might be causing this?

**Comment by zyeking** [comment]
> @zyeking @lpzhi @lyr1994 都是 swag v1.6.3 版本吗？

是的

**Comment by eddycjy** [comment]
@zyeking 你这个问题之前已经修复了，目前 go-gin-example 并不存在相关的代码，若还是存在，请附上相应链接，感谢。

**Comment by Benjamin-UnderWood** [comment]
2020/06/24 17:39:18 ParseComment error in file routers/api/v1/tag.go :can not find schema type: "v1.json"
按照文档写仍然存在这个问题

**Comment by FirmDiary** [comment]
![image](https://user-images.githubusercontent.com/34047545/146898316-b55c5ce3-300e-499d-b8ef-5cbcfd689351.png)

**Comment by hujianli94** [comment]
![image](https://user-images.githubusercontent.com/34468329/175908391-037e5b47-9870-4129-921c-b6fcfb7fc5f0.png)
请问一下这个报错是是你们意思呢？
