### ISSUE TITLE
model与dao写在一起了

### ISSUE THREAD

**Issue by tylitianrui** [eddycjy/go-gin-example#89]
个人建议，把model与dao层还是分离比较好

**Comment by owen800q** [comment]
有什麼好處嗎

**Comment by Yukibana** [comment]
dao层可以用接口实现，然后弄依赖反转什么的。就是支持多种数据库存储而不用修改业务层代码的意思吧。java和c#的.net core都有类似的概念

**Comment by eddycjy** [comment]
因为这个项目太小了，所以我当时并没有将其拆开（项目太小，觉得多此一举），因此在正式的长期迭代项目中，可拆开，具体依据实际项目情况各自定夺即可。
