### ISSUE TITLE
请教一个问题，如果表字段特别多的情况下，怎么优雅的创建、更新数据

### ISSUE THREAD

**Issue by dmwin72015** [eddycjy/go-gin-example#93]
如果表字段特别多的情况下，我看了下，项目是 要么传入指定字段，或者用map来转换，
如果字段比较多，感觉写法有点啰嗦啊

**Comment by eddycjy** [comment]
@dmwin72015  传入结构体，也就是 `struct`，一般我们会根据情况选用，因为这个项目字段比较少，所以就没直接用 `strcut`。
