### ISSUE TITLE
章节 “Gin搭建Blog API's （三）” 中添加文章的代码有误，Article 类型定义中 created_by 应为 created_on

### ISSUE THREAD

**Issue by lewis-li** [eddycjy/go-gin-example#95]

**Comment by eddycjy** [comment]
@lewis-li 请问你指的具体哪里，能够说明详细一点？

`CreatedOn` 字段的话，在基础 Model 中已经定义了，传送门：https://eddycjy.com/posts/go/gin/2018-02-11-api-01/#%E7%BC%96%E5%86%99-models-init 。
