### ISSUE TITLE
小白提问：post json数据一直错误

### ISSUE THREAD

**Issue by plsof** [eddycjy/go-gin-example#98]
➜  ~ curl -X POST "http://127.0.0.1:8000/api/v1/tags" -H "accept: application/json" -H "Content-Type: application/json" -d '{created_by: \"pdd\", state: 0, name: \"test\"}'
{"code":400,"msg":"请求参数错误","data":null}

有大佬提示下这个应该怎么弄吗

**Comment by plsof** [comment]
上面忘了加引号 ~ curl -X POST "http://127.0.0.1:8000/api/v1/tags" -H "accept: application/json" -H "Content-Type: application/json" -d "{created_by:\"pdd\", state:0, name:\"test\"}"

**Comment by eddycjy** [comment]
@plsof 没有代码的话，只能根据我的示例去猜测。
既然他报“请求参数错误”，那你进到判断入参的地方具体观察是哪里有问题就好了。
