### ISSUE TITLE
swagger 使用错误了，现在版本更新了

### ISSUE THREAD

**Issue by lpzhi** [eddycjy/go-gin-example#99]
url := ginSwagger.URL("http://localhost:8090/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

**Comment by eddycjy** [comment]
@lpzhi 请给出受影响的依赖库的具体版本信息？

目前我本地版本是 v1.6.3，而据我观察 @easonlin404 所发布的 swag 目前仍在 v1.6.5，属于修订版本，应该是不存在破坏性修改才对。

**Comment by eddycjy** [comment]
我已经把 gin-swagger 升级到了 v1.2.0，其在 `ginSwagger.WrapHandler` API 新增了 `confs` 参数，你所提到的 `ginSwagger.URL` 方法可用于指定 swagger.json 的读取，但由于本示例项目的 swagger.json 就是在同应用下，因此并不会造成问题。

若有其它问题请附上详细重现步骤。
